Repository suhsein/2022_OSS_Teamproject, pull requests merged in 2022-11, with the labels that each got.

#31 feat : 랜덤 인사 기능 추가
  .eslintrc.js
  greeting.js
  index.js
Labels: enhancement

#40 Feature/2-1 구현
  .gitignore
  .gitmessage.txt
  index.js
  schedule.js
  test.spec.js
Labels: enhancement

#41 feat 2: 스케줄 딕셔너리 모듈로 분리
  .gitignore
  dept.txt
  exp.js
  getschedule.js
  haksa.txt
  haksaguide.js
  index.js
  schedule.js
Labels: 기능 수정

#42 feat : feature2 테스트 코드 수정
  test/feature-1.spec.js
  test/feature-2.spec.js
Labels: enhancement

#49 Feature/1
  .github/workflows/feature-1-mocha.yml
  .github/workflows/feature-2-mocha.yml
  greeting.js
  index.js
  test/Readme.md
  test/feature-1.spec.js
Labels: bug

#51 Feature/2
  .gitignore
  .gitmessage.txt
  checkDate.js
  getScheduleDict.js
  index.js
  schedule.js
  test.txt
Labels: enhancement

#54 최종 수정
  .eslintrc.js
  Office.js
  dept.txt
  getOfficeDict.js
  greeting.js
  index.js
  test.txt
  test/feature-4.spec.js
Labels: bug, enhancement

#55 Feature/4
  getOfficeDict.js
  index.js
  test/feature-4.spec.js
Labels: 기능 수정
